from flask_covid19_app.blueprints.data_ecdc.ecdc_model_import import EcdcImport
from flask_covid19_app.blueprints.data_divi.divi_model_import import DiviImport

from flask_covid19_app.blueprints.data_ecdc.ecdc_model_import import EcdcFlat

from flask_covid19_app.blueprints.data_ecdc.ecdc_service import EcdcService
from flask_covid19_app.blueprints.data_divi.divi_service import DiviService

