@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_05 {
    usecase Number_of_COVID19_patients_in_hospital as UC280
    usecase Number_of_COVID19_patients_in_hospital_per_million as UC281
    usecase Number_of_COVID19_patients_in_intensive_care__ICU as UC282
    usecase Number_of_people_fully_vaccinated_against_COVID19 as UC283
    usecase Number_of_people_who_received_at_least_one_dose_of_COVID19_vaccine as UC284
    usecase Number_of_tests_per_confirmed_case_vs_Total_confirmed_COVID19_cases_per_million_people as UC285
    usecase Parks_and_outdoor_spaces__How_did_the_Number_of_visitors_change_since_the_beginning_of_the_pandemic as UC286
    usecase Per_capita__COVID19_tests_vs_Confirmed_deaths as UC287
    usecase Per_capita__tests_for_COVID19_vs_Confirmed_cases as UC288
    usecase Public_information_campaigns_on_the_COVID19_pandemic as UC289
    usecase Public_transport_closures_during_the_COVID19_pandemic as UC290
    usecase Residential_areas__How_did_the_time_spent_at_home_change_since_the_beginning_of_the_pandemic as UC291
    usecase Restrictions_on_internal_movement_during_the_COVID19_pandemic as UC292
    usecase Restrictions_on_public_gatherings_in_the_COVID19_pandemic as UC293
    usecase Retail_and_recreation__How_did_the_Number_of_visitors_change_since_the_beginning_of_the_pandemic as UC294
    usecase School_closures_during_the_COVID19_pandemic as UC295
    usecase Share_of_COVID19_tests_that_were_positive_Over_time__since_5th_death_was_confirmed as UC296
    usecase Share_of_people_who_received_at_least_one_dose_of_COVID19_vaccine as UC297
    usecase Share_of_the_population_fully_vaccinated_against_COVID19 as UC298
    usecase Share_of_Total_COVID19_tests_that_were_positive as UC299
}
am --> UC280
am --> UC281
am --> UC282
am --> UC283
am --> UC284
am --> UC285
am --> UC286
am --> UC287
am --> UC288
am --> UC289
am --> UC290
am --> UC291
am --> UC292
am --> UC293
am --> UC294
am --> UC295
am --> UC296
am --> UC297
am --> UC298
vu --> UC299
@enduml
