@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_08 {
    usecase Total_COVID19_Tests_conducted_vs_Confirmed_cases as UC340
    usecase Total_COVID19_Tests_conducted_vs_Confirmed_cases_Positive_rate_comparison as UC341
    usecase Total_COVID19_Tests_conducted_vs_Confirmed_cases_per_million as UC342
    usecase Total_COVID19_Tests_for_each_confirmed_case as UC343
    usecase Total_COVID19_Tests_for_each_confirmed_case_Bar_chart as UC344
    usecase Total_COVID19_tests_per_1000_people_Line_chart as UC345
    usecase Total_COVID19_tests_per_1000_people_Map_chart as UC346
    usecase Total_COVID19_tests_per_1000_people_Bar_chart as UC347
    usecase Total_COVID19_tests_per_1000_vs_GDP_per_capita as UC348
    usecase Total_COVID19_tests_per_1000__how_are_testing_rates_changing__Since_Daily_new_confirmed_deaths_due_to_COVID19_reached_0p1_per_million as UC349
    usecase Total_COVID19_tests_per_1000__how_are_testing_rates_changing__Since_Daily_new_confirmed_deaths_due_to_COVID19_reached_0p1_per_million as UC350
    usecase Total_and_Daily_confirmed_COVID19_cases as UC351
    usecase Total_and_Daily_confirmed_COVID19_cases_per_million_people as UC352
    usecase Total_confirmed_COVID19_cases_By_Income_Group as UC353
    usecase Total_confirmed_COVID19_cases_per_million_people_Map_and_country_time_series as UC354
    usecase Total_confirmed_COVID19_cases_per_million__how_rapidly_are_they_increasing__Trajectories as UC355
    usecase Total_confirmed_COVID19_cases_vs_deaths_per_million as UC356
    usecase Total_confirmed_COVID19_cases__by_source as UC357
    usecase Total_confirmed_COVID19_cases__how_rapidly_are_they_increasing__Trajectories as UC358
    usecase Total_confirmed_COVID19_deaths_Map_and_country_time_series as UC359
}
am --> UC340
am --> UC341
am --> UC342
am --> UC343
am --> UC344
am --> UC345
am --> UC346
am --> UC347
am --> UC348
am --> UC349
am --> UC350
am --> UC351
am --> UC352
am --> UC353
am --> UC354
am --> UC355
am --> UC356
am --> UC357
am --> UC358
am --> UC359
@enduml
