@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_01 {
    usecase Biweekly_change_in_confirmed_COVID19_cases as UC200
    usecase Biweekly_change_in_confirmed_COVID19_deaths as UC201
    usecase Biweekly_confirmed_COVID19_cases as UC202
    usecase Biweekly_confirmed_COVID19_cases_per_million_people as UC203
    usecase Biweekly_confirmed_COVID19_deaths as UC204
    usecase Biweekly_confirmed_COVID19_deaths_per_million_people as UC205
    usecase COVID19_Testing_Policies as UC206
    usecase COVID19_Vaccination_Policy as UC207
    usecase COVID19_death_rate_vs_Population_density as UC208
    usecase COVID19_vaccine_doses_administered as UC209
    usecase COVID19_vaccine_doses_administered_per_100_people as UC210
    usecase COVID19__Daily_new_confirmed_cases_vs_cumulative_cases as UC211
    usecase COVID19__Daily_new_confirmed_cases_vs_cumulative_cases as UC212
    usecase COVID19__Daily_tests_vs_Daily_new_confirmed_cases as UC213
    usecase COVID19__Daily_tests_vs_Daily_new_confirmed_cases_per_million as UC214
    usecase COVID19__Stringency_Index as UC215
    usecase Cancellation_of_public_events_during_COVID19_pandemic as UC216
    usecase Case_fatality_rate_of_COVID19_vs_Median_age_of_the_population as UC217
    usecase Case_fatality_rate_of_the_ongoing_COVID19_pandemic as UC218
    usecase Case_fatality_rate_vs_Tests_per_confirmed_case as UC219
}
am --> UC200
am --> UC201
am --> UC202
am --> UC203
am --> UC204
am --> UC205
am --> UC206
am --> UC207
am --> UC208
am --> UC209
am --> UC210
am --> UC211
am --> UC212
am --> UC213
am --> UC214
am --> UC215
am --> UC216
am --> UC217
am --> UC218
am --> UC219
@enduml
