@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_06 {
    usecase Share_who_would_get_a_COVID19_vaccine_if_it_was_available_to_them_this_week as UC300
    usecase Stay_at_home_requirements_during_the_COVID19_pandemic as UC301
    usecase Tests_conducted_per_new_confirmed_case_of_COVID19 as UC302
    usecase Tests_per_confirmed_case__Total_vs_Case_fatality_rate as UC303
    usecase Tests_per_thousand_since_the_100th_confirmed_case_of_COVID19 as UC304
    usecase Tests_per_thousand_since_the_5th_confirmed_death_due_to_COVID19 as UC305
    usecase The_share_of_COVID19_Tests_that_are_positive as UC306
    usecase Total_COVID19_testsLine_chart as UC307
    usecase Total_COVID19_testsMap_chart as UC308
    usecase Total_COVID19_Tests_conducted_vs_Confirmed_cases as UC309
    usecase Total_COVID19_Tests_conducted_vs_Confirmed_cases_Positive_rate_comparison as UC310
    usecase Total_COVID19_Tests_conducted_vs_Confirmed_cases_per_million as UC311
    usecase Total_COVID19_Tests_for_each_confirmed_case as UC312
    usecase Total_COVID19_Tests_for_each_confirmed_case_Bar_chart as UC313
    usecase Total_COVID19_tests_per_1000_people_Line_chart as UC314
    usecase Total_COVID19_tests_per_1000_people_Map_chart as UC315
    usecase Total_COVID19_tests_per_1000_people_Bar_chart as UC316
    usecase Total_COVID19_tests_per_1000_vs_GDP_per_capita as UC317
    usecase Total_COVID19_tests_per_1000__how_are_testing_rates_changing__Since_Daily_new_confirmed_deaths_due_to_COVID19_reached_0p1_per_million as UC318
    usecase Total_COVID19_tests_per_1000__how_are_testing_rates_changing__Since_Daily_new_confirmed_deaths_due_to_COVID19_reached_0p1_per_million as UC319
}
am --> UC300
am --> UC301
am --> UC302
am --> UC303
am --> UC304
am --> UC305
am --> UC306
am --> UC307
am --> UC308
am --> UC309
am --> UC310
am --> UC311
am --> UC312
am --> UC313
am --> UC314
am --> UC315
am --> UC316
am --> UC317
am --> UC318
am --> UC319

@enduml
