@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_07 {
    usecase Public_information_campaigns_on_the_COVID19_pandemic as UC320
    usecase Public_transport_closures_during_the_COVID19_pandemic as UC321
    usecase Residential_areas__How_did_the_time_spent_at_home_change_since_the_beginning_of_the_pandemic as UC322
    usecase Restrictions_on_internal_movement_during_the_COVID19_pandemic as UC323
    usecase Restrictions_on_public_gatherings_in_the_COVID19_pandemic as UC324
    usecase Retail_and_recreation__How_did_the_Number_of_visitors_change_since_the_beginning_of_the_pandemic as UC325
    usecase School_closures_during_the_COVID19_pandemic as UC326
    usecase Share_of_COVID19_tests_that_were_positive_Over_time__since_5th_death_was_confirmed as UC327
    usecase Share_of_people_who_received_at_least_one_dose_of_COVID19_vaccine as UC328
    usecase Share_of_the_population_fully_vaccinated_against_COVID19 as UC329
    usecase Share_of_Total_COVID19_tests_that_were_positive as UC330
    usecase Share_who_would_get_a_COVID19_vaccine_if_it_was_available_to_them_this_week as UC331
    usecase Stay_at_home_requirements_during_the_COVID19_pandemic as UC332
    usecase Tests_conducted_per_new_confirmed_case_of_COVID19 as UC333
    usecase Tests_per_confirmed_case__Total_vs_Case_fatality_rate as UC334
    usecase Tests_per_thousand_since_the_100th_confirmed_case_of_COVID19 as UC335
    usecase Tests_per_thousand_since_the_5th_confirmed_death_due_to_COVID19 as UC336
    usecase The_share_of_COVID19_Tests_that_are_positive as UC337
    usecase Total_COVID19_tests_Line_chart as UC338
    usecase Total_COVID19_tests_Map_chart as UC339
}
am --> UC320
am --> UC321
am --> UC322
am --> UC323
am --> UC324
am --> UC325
am --> UC326
am --> UC327
am --> UC328
am --> UC329
am --> UC330
am --> UC331
am --> UC332
am --> UC333
am --> UC334
am --> UC335
am --> UC336
am --> UC337
am --> UC338
am --> UC339

@enduml
