@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_09 {
    usecase Total_confirmed_COVID19_deaths_By_Income_Group as UC360
    usecase Total_confirmed_COVID19_deaths_and_cases_per_million_people as UC361
    usecase Total_confirmed_COVID19_deaths_per_million_people as UC362
    usecase Total_confirmed_COVID19_deaths_per_million_vs_GDP_per_capita as UC363
    usecase Total_confirmed_COVID19_deaths_per_million__how_rapidly_are_they_increasing as UC364
    usecase Total_confirmed_COVID19_deaths__how_rapidly_are_they_increasing__Trajectories as UC365
    usecase Total_confirmed_deaths_due_to_COVID19_vs_Population as UC366
    usecase Total_confirmed_deaths_from_COVID19__by_source as UC367
    usecase Total_Number_of_COVID19_Tests_per_confirmed_case as UC368
    usecase Transit_stations__How_did_the_Number_of_visitors_change_since_the_beginning_of_the_pandemic as UC369
    usecase Week_by_week_change_in_confirmed_COVID19_cases as UC370
    usecase Week_by_week_change_of_confirmed_COVID19_cases_vs_GDP_per_capita as UC371
    usecase Week_by_week_change_of_confirmed_COVID19_deaths as UC372
    usecase Week_by_week_change_of_confirmed_COVID19_deaths_vs_GDP_per_capita as UC373
    usecase Weekly_case_growth_rate_vs_Daily_case_rate as UC374
    usecase Weekly_confirmed_COVID19_cases as UC375
    usecase Weekly_confirmed_COVID19_cases_per_million_people as UC376
    usecase Weekly_confirmed_COVID19_deaths as UC377
    usecase Weekly_confirmed_COVID19_deaths_per_million_people as UC378
    usecase Weekly_death_growth_rate_vs_Daily_death_rate as UC379
}
am --> UC360
am --> UC361
am --> UC362
am --> UC363
am --> UC364
am --> UC365
am --> UC366
am --> UC367
am --> UC368
am --> UC369
am --> UC370
am --> UC371
am --> UC372
am --> UC373
am --> UC374
am --> UC375
am --> UC376
am --> UC377
am --> UC378
am --> UC379
@enduml
