@startuml
left to right direction
actor Visitor as vu
package user {
	actor SysAdmin as su
	actor Admin as au
}
package owid_views_frontend_visual_data_1 {
    usecase owid_report_Biweekly_change_in_confirmed_COVID19_cases as UC200
    usecase owid_report_Biweekly_change_in_confirmed_COVID19_deaths as UC201
    usecase owid_report_Biweekly_confirmed_COVID19_cases as UC202
    usecase owid_report_Biweekly_confirmed_COVID19_cases_per_million_people as UC203
    usecase owid_report_Biweekly_confirmed_COVID19_deaths as UC204
    usecase owid_report_Biweekly_confirmed_COVID19_deaths_per_million_people as UC205
    usecase owid_report_COVID19_Testing_Policies as UC206
    usecase owid_report_COVID19_Vaccination_Policy as UC207
    usecase owid_report_COVID19_death_rate_vs_Population_density as UC208
    usecase owid_report_COVID19_vaccine_doses_administered as UC209
    usecase owid_report_COVID19_vaccine_doses_administered_per_100_people as UC210
    usecase owid_report_COVID19__Daily_new_confirmed_cases_vs_cumulative_cases as UC211
    usecase owid_report_COVID19__Daily_new_confirmed_cases_vs_cumulative_cases as UC212
    usecase owid_report_COVID19__Daily_tests_vs_Daily_new_confirmed_cases as UC213
    usecase owid_report_COVID19__Daily_tests_vs_Daily_new_confirmed_cases_per_million as UC214
    usecase owid_report_COVID19__Stringency_Index as UC215
    usecase owid_report_Cancellation_of_public_events_during_COVID19_pandemic as UC216
    usecase owid_report_Case_fatality_rate_of_COVID19_vs_Median_age_of_the_population as UC217
    usecase owid_report_Case_fatality_rate_of_the_ongoing_COVID19_pandemic as UC218
    usecase owid_report_Case_fatality_rate_vs_Tests_per_confirmed_case as UC219
    usecase owid_report_Case_fatality_rate_vs_Total_confirmed_COVID19_deaths as UC220
    usecase owid_report_Confirmed_COVID19_deaths_per_million_vs_GDP_per_capita as UC221
    usecase owid_report_Confirmed_COVID19_deaths_vs_Population_density as UC222
    usecase owid_report_Cumulative_COVID19_tests_confirmed_cases_and_deaths as UC223
    usecase owid_report_Cumulative_COVID19_tests_confirmed_cases_and_deaths_per_million_people as UC224
    usecase owid_report_Cumulative_confirmed_COVID19_casesMap_and_country_time_series as UC225
    usecase owid_report_Cumulative_confirmed_COVID19_cases_By_Region as UC226
    usecase owid_report_Cumulative_confirmed_COVID19_cases_per_million_vs_GDP_per_capita as UC227
    usecase owid_report_Cumulative_confirmed_COVID19_deaths_By_Region as UC228
    usecase owid_report_Cumulative_confirmed_COVID19_deaths_and_cases as UC229
    usecase owid_report_Cumulative_confirmed_COVID19_deaths_vs_cases as UC230
}
vu --> UC200
vu --> UC201
vu --> UC202
vu --> UC203
vu --> UC204
vu --> UC205
vu --> UC206
vu --> UC207
vu --> UC208
vu --> UC209
vu --> UC210
vu --> UC211
vu --> UC212
vu --> UC213
vu --> UC214
vu --> UC215
vu --> UC216
vu --> UC217
vu --> UC218
vu --> UC219
vu --> UC220
vu --> UC221
vu --> UC222
vu --> UC223
vu --> UC224
vu --> UC225
vu --> UC226
vu --> UC227
vu --> UC228
vu --> UC229
vu --> UC230
@enduml
