@startuml
left to right direction
'https://plantuml.com/class-diagram

package data_all.framework {
    abstract class AllImport {}
    abstract class AllDateReported {}
    abstract class AllLocation {}
    abstract class AllLocationGroup {}
    abstract class AllFactTable {}

    AllLocation "1" *--> "*" AllLocationGroup : region
    AllFactTable "1" *--> "*" AllLocation : country
    AllFactTable "1" *--> "*" AllDateReported : date_reported
}

package data_who.model {
    entity WhoData {}
    entity WhoDateReported {}
    entity WhoImport {}
    entity WhoCountry {}
    entity WhoCountryRegion {}

    AllImport <|- WhoImport
    AllDateReported <|- WhoDateReported
    AllLocation <|- WhoCountry
    AllLocationGroup <|- WhoCountryRegion
    AllFactTable <|- WhoData

    WhoCountry "1" *--> "*" WhoCountryRegion : region
    WhoData "1" *--> "*" WhoCountry : country
    WhoData "1" *--> "*" WhoDateReported : date_reported
}

@enduml
