from flask_covid19 import OwidImport, OwidFlat


class OwidImportFactory:

    @classmethod
    def create_new(cls, date_reported, d, row):
        o = OwidImport(
            date_reported_import_str=date_reported,
            iso_code=row['iso_code'],
            date=date_reported,
            continent=row['continent'],
            location=row['location'],
            total_cases=row['total_cases'],
            new_cases=row['new_cases'],
            new_cases_smoothed=row['new_cases_smoothed'],
            total_deaths=row['total_deaths'],
            new_deaths=row['new_deaths'],
            new_deaths_smoothed=row['new_deaths_smoothed'],
            total_cases_per_million=row['total_cases_per_million'],
            new_cases_per_million=row['new_cases_per_million'],
            new_cases_smoothed_per_million=row['new_cases_smoothed_per_million'],
            total_deaths_per_million=row['total_deaths_per_million'],
            new_deaths_per_million=row['new_deaths_per_million'],
            new_deaths_smoothed_per_million=row['new_deaths_smoothed_per_million'],
            reproduction_rate=row['reproduction_rate'],
            icu_patients=row['icu_patients'],
            icu_patients_per_million=row['icu_patients_per_million'],
            hosp_patients=row['hosp_patients'],
            hosp_patients_per_million=row['hosp_patients_per_million'],
            weekly_icu_admissions=row['weekly_icu_admissions'],
            weekly_icu_admissions_per_million=row['weekly_icu_admissions_per_million'],
            weekly_hosp_admissions=row['weekly_hosp_admissions'],
            weekly_hosp_admissions_per_million=row['weekly_hosp_admissions_per_million'],
            new_tests=row['new_tests'],
            total_tests=row['total_tests'],
            total_tests_per_thousand=row['total_tests_per_thousand'],
            new_tests_per_thousand=row['new_tests_per_thousand'],
            new_tests_smoothed=row['new_tests_smoothed'],
            new_tests_smoothed_per_thousand=row['new_tests_smoothed_per_thousand'],
            positive_rate=row['positive_rate'],
            tests_per_case=row['tests_per_case'],
            tests_units=row['tests_units'],
            total_vaccinations=row['total_vaccinations'],
            people_vaccinated=row['people_vaccinated'],
            people_fully_vaccinated=row['people_fully_vaccinated'],
            new_vaccinations=row['new_vaccinations'],
            new_vaccinations_smoothed=row['new_vaccinations_smoothed'],
            total_vaccinations_per_hundred=row['total_vaccinations_per_hundred'],
            people_vaccinated_per_hundred=row['people_vaccinated_per_hundred'],
            people_fully_vaccinated_per_hundred=row['people_fully_vaccinated_per_hundred'],
            new_vaccinations_smoothed_per_million=row['new_vaccinations_smoothed_per_million'],
            stringency_index=row['stringency_index'],
            population=row['population'],
            population_density=row['population_density'],
            median_age=row['median_age'],
            aged_65_older=row['aged_65_older'],
            aged_70_older=row['aged_70_older'],
            gdp_per_capita=row['gdp_per_capita'],
            extreme_poverty=row['extreme_poverty'],
            cardiovasc_death_rate=row['cardiovasc_death_rate'],
            diabetes_prevalence=row['diabetes_prevalence'],
            female_smokers=row['female_smokers'],
            male_smokers=row['male_smokers'],
            handwashing_facilities=row['handwashing_facilities'],
            hospital_beds_per_thousand=row['hospital_beds_per_thousand'],
            life_expectancy=row['life_expectancy'],
            human_development_index=row['human_development_index'],
            datum=d.datum,
            processed_update=False,
            processed_full_update=False,
        )
        return o


class OwidFlatFactory:

    @classmethod
    def create_new(cls, d, row):
        f = OwidFlat(
            date_reported_import_str=d.date_reported_import_str,
            datum=d.datum,
            year=d.year,
            month=d.month,
            day_of_month=d.day_of_month,
            day_of_week=d.day_of_week,
            week_of_year=d.week_of_year,
            day_of_year=d.day_of_year,
            year_week=d.year_week,
            year_day_of_year=d.year_day_of_year,
            year_month=d.year_month,
            location=row['location'],
            location_group=row['continent'],
            location_code=row['iso_code'],
            processed_update=False,
            processed_full_update=False,
            #
            total_cases=0.0 if '' == row['total_cases'] else float(row['total_cases']),
            new_cases=0.0 if '' == row['new_cases'] else float(row['new_cases']),
            new_cases_smoothed=0.0 if '' == row['new_cases_smoothed'] else float(row['new_cases_smoothed']),
            total_deaths=0.0 if '' == row['total_deaths'] else float(row['total_deaths']),
            new_deaths=0.0 if '' == row['new_deaths'] else float(row['new_deaths']),
            new_deaths_smoothed=0.0 if '' == row['new_deaths_smoothed'] else float(row['new_deaths_smoothed']),
            total_cases_per_million=0.0 if '' == row['total_cases_per_million'] else float(row['total_cases_per_million']),
            new_cases_per_million=0.0 if '' == row['new_cases_per_million'] else float(row['new_cases_per_million']),
            new_cases_smoothed_per_million=0.0 if '' == row['new_cases_smoothed_per_million'] else float(row['new_cases_smoothed_per_million']),
            total_deaths_per_million=0.0 if '' == row['total_deaths_per_million'] else float(row['total_deaths_per_million']),
            new_deaths_per_million=0.0 if '' == row['new_deaths_per_million'] else float(row['new_deaths_per_million']),
            new_deaths_smoothed_per_million=0.0 if '' == row['new_deaths_smoothed_per_million'] else float(row['new_deaths_smoothed_per_million']),
            reproduction_rate=0.0 if '' == row['reproduction_rate'] else float(row['reproduction_rate']),
            icu_patients=0.0 if '' == row['icu_patients'] else float(row['icu_patients']),
            icu_patients_per_million=0.0 if '' == row['icu_patients_per_million'] else float(row['icu_patients_per_million']),
            hosp_patients=0.0 if '' == row['hosp_patients'] else float(row['hosp_patients']),
            hosp_patients_per_million=0.0 if '' == row['hosp_patients_per_million'] else float(row['hosp_patients_per_million']),
            weekly_icu_admissions=0.0 if '' == row['weekly_icu_admissions'] else float(row['weekly_icu_admissions']),
            weekly_icu_admissions_per_million=0.0 if '' == row['weekly_icu_admissions_per_million'] else float(row['weekly_icu_admissions_per_million']),
            weekly_hosp_admissions=0.0 if '' == row['weekly_hosp_admissions'] else float(row['weekly_hosp_admissions']),
            weekly_hosp_admissions_per_million=0.0 if '' == row['weekly_hosp_admissions_per_million'] else float(row['weekly_hosp_admissions_per_million']),
            new_tests=0.0 if '' == row['new_tests'] else float(row['new_tests']),
            total_tests=0.0 if '' == row['total_tests'] else float(row['total_tests']),
            total_tests_per_thousand=0.0 if '' == row['total_tests_per_thousand'] else float(row['total_tests_per_thousand']),
            new_tests_per_thousand=0.0 if '' == row['new_tests_per_thousand'] else float(row['new_tests_per_thousand']),
            new_tests_smoothed=0.0 if '' == row['new_tests_smoothed'] else float(row['new_tests_smoothed']),
            new_tests_smoothed_per_thousand=0.0 if '' == row['new_tests_smoothed_per_thousand'] else float(row['new_tests_smoothed_per_thousand']),
            positive_rate=0.0 if '' == row['positive_rate'] else float(row['positive_rate']),
            tests_per_case=0.0 if '' == row['tests_per_case'] else float(row['tests_per_case']),
            tests_units=row['tests_units'],
            total_vaccinations=0.0 if '' == row['total_vaccinations'] else float(row['total_vaccinations']),
            people_vaccinated=0.0 if '' == row['people_vaccinated'] else float(row['people_vaccinated']),
            people_fully_vaccinated=0.0 if '' == row['people_fully_vaccinated'] else float(row['people_fully_vaccinated']),
            new_vaccinations=0.0 if '' == row['new_vaccinations'] else float(row['new_vaccinations']),
            new_vaccinations_smoothed=0.0 if '' == row['new_vaccinations_smoothed'] else float(row['new_vaccinations_smoothed']),
            total_vaccinations_per_hundred=0.0 if '' == row['total_vaccinations_per_hundred'] else float(row['total_vaccinations_per_hundred']),
            people_vaccinated_per_hundred=0.0 if '' == row['people_vaccinated_per_hundred'] else float(row['people_vaccinated_per_hundred']),
            people_fully_vaccinated_per_hundred=0.0 if '' == row['people_vaccinated_per_hundred'] else float(row['people_vaccinated_per_hundred']),
            new_vaccinations_smoothed_per_million=0.0 if '' == row['new_vaccinations_smoothed_per_million'] else float(row['new_vaccinations_smoothed_per_million']),
            stringency_index=0.0 if '' == row['stringency_index'] else float(row['stringency_index']),
            population=0.0 if '' == row['population'] else float(row['population']),
            population_density=0.0 if '' == row['population_density'] else float(row['population_density']),
            median_age=0.0 if '' == row['median_age'] else float(row['median_age']),
            aged_65_older=0.0 if '' == row['aged_65_older'] else float(row['aged_65_older']),
            aged_70_older=0.0 if '' == row['aged_70_older'] else float(row['aged_70_older']),
            gdp_per_capita=0.0 if '' == row['gdp_per_capita'] else float(row['gdp_per_capita']),
            extreme_poverty=0.0 if '' == row['extreme_poverty'] else float(row['extreme_poverty']),
            cardiovasc_death_rate=0.0 if '' == row['cardiovasc_death_rate'] else float(row['cardiovasc_death_rate']),
            diabetes_prevalence=0.0 if '' == row['diabetes_prevalence'] else float(row['diabetes_prevalence']),
            female_smokers=0.0 if '' == row['female_smokers'] else float(row['female_smokers']),
            male_smokers=0.0 if '' == row['male_smokers'] else float(row['male_smokers']),
            handwashing_facilities=0.0 if '' == row['handwashing_facilities'] else float(row['handwashing_facilities']),
            hospital_beds_per_thousand=0.0 if '' == row['hospital_beds_per_thousand'] else float(row['hospital_beds_per_thousand']),
            life_expectancy=0.0 if '' == row['life_expectancy'] else float(row['life_expectancy']),
            human_development_index=0.0 if '' == row['human_development_index'] else float(row['human_development_index']),
        )
        return f
