@startuml
left to right direction
'https://plantuml.com/class-diagram

package data_all.framework {
    abstract class AllImport {}
    abstract class AllDateReported {}
    abstract class AllLocation {}
    abstract class AllLocationGroup {}
    abstract class AllFactTable {}

    AllLocation "1" *--> "*" AllLocationGroup : region
    AllFactTable "1" *--> "*" AllLocation : country
    AllFactTable "1" *--> "*" AllDateReported : date_reported
}

package data_ecdc {
    entity EcdcImport {}
    entity EcdcData {}
    entity EcdcDateReported {}
    entity EcdcCountry {}
    entity EcdcContinent {}

    AllImport <|- EcdcImport
    AllDateReported <|- EcdcDateReported
    AllLocation <|- EcdcCountry
    AllLocationGroup <|- EcdcContinent
    AllFactTable <|- EcdcData

    EcdcCountry "1" *--> "*" EcdcContinent : region
    EcdcData "1" *--> "*" EcdcCountry : country
    EcdcData "1" *--> "*" EcdcDateReported : date_reported
}

@enduml
