@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_02 {
    usecase Case_fatality_rate_vs_Total_confirmed_COVID19_deaths as UC220
    usecase Confirmed_COVID19_deaths_per_million_vs_GDP_per_capita as UC221
    usecase Confirmed_COVID19_deaths_vs_Population_density as UC222
    usecase Cumulative_COVID19_tests_confirmed_cases_and_deaths as UC223
    usecase Cumulative_COVID19_tests_confirmed_cases_and_deaths_per_million_people as UC224
    usecase Cumulative_confirmed_COVID19_casesMap_and_country_time_series as UC225
    usecase Cumulative_confirmed_COVID19_cases_By_Region as UC226
    usecase Cumulative_confirmed_COVID19_cases_per_million_vs_GDP_per_capita as UC227
    usecase Cumulative_confirmed_COVID19_deaths_By_Region as UC228
    usecase Cumulative_confirmed_COVID19_deaths_and_cases as UC229
    usecase Cumulative_confirmed_COVID19_deaths_vs_cases as UC230
    usecase Daily_COVID19_Tests as UC231
    usecase Daily_COVID19_Tests as UC232
    usecase Daily_COVID19_tests_per_thousand_people as UC233
    usecase Daily_COVID19_tests_per_thousand_people_Rolling_7day_average as UC234
    usecase Daily_COVID19_vaccine_doses_administered as UC235
    usecase Daily_COVID19_vaccine_doses_administered_per_100_people as UC236
    usecase Daily_and_Total_confirmed_COVID19_deaths as UC237
    usecase Daily_and_Total_confirmed_COVID19_deaths_per_million as UC238
    usecase Daily_confirmed_COVID19_casesMap_and_country_time_series as UC239
}
am --> UC220
am --> UC221
am --> UC222
am --> UC223
am --> UC224
am --> UC225
am --> UC226
am --> UC227
am --> UC228
am --> UC229
am --> UC230
am --> UC231
am --> UC232
am --> UC233
am --> UC234
am --> UC235
am --> UC236
am --> UC237
am --> UC238
am --> UC239
@enduml
