@startuml
left to right direction

package app_user {
	actor AnonymousVisitor as av
	actor AppManager as am
	actor CliUser as cu

	av <|-- am
	am <|-- cu
}

package owid_report_03 {
    usecase Daily_confirmed_COVID19_casesStacked_area_chart__by_world_region as UC240
    usecase Daily_confirmed_COVID19_cases_and_deaths as UC241
    usecase Daily_confirmed_COVID19_cases_per_million_people as UC242
    usecase Daily_confirmed_COVID19_cases_per_million__3day_rolling_average as UC243
    usecase Daily_confirmed_COVID19_cases_per_million__which_countries_are_bending_the_curve__Trajectories as UC244
    usecase Daily_confirmed_COVID19_cases__rolling_7day_average as UC245
    usecase Daily_confirmed_COVID19_cases__which_countries_are_bending_the_curve as UC246
    usecase Daily_confirmed_COVID19_deathsMap_and_time_series as UC247
    usecase Daily_confirmed_COVID19_deathsBy_Region as UC248
    usecase Daily_confirmed_COVID19_deaths_per_million_people as UC249
    usecase Daily_confirmed_COVID19_deaths_per_million__3day_rolling_average as UC250
    usecase Daily_confirmed_COVID19_deaths_per_million__rolling_7day_average as UC251
    usecase Daily_confirmed_COVID19_deaths_per_million__which_countries_are_bending_the_curve__Trajectories as UC252
    usecase Daily_confirmed_COVID19_deaths__rolling_7day_average as UC253
    usecase Daily_confirmed_COVID19_deaths__which_countries_are_bending_the_curve__Trajectories as UC254
    usecase Daily_new_confirmed_COVID19_cases_and_deaths as UC255
    usecase Daily_new_confirmed_cases_of_COVID19 as UC256
    usecase Daily_new_confirmed_cases_of_COVID19 as UC257
    usecase Daily_new_confirmed_cases_of_COVID19_per_million_people as UC258
    usecase Daily_new_estimated_COVID19_infections_from_the_ICL_model as UC259
}
am --> UC240
am --> UC241
am --> UC242
am --> UC243
am --> UC244
am --> UC245
am --> UC246
am --> UC247
am --> UC248
am --> UC249
am --> UC250
am --> UC251
am --> UC252
am --> UC253
am --> UC254
am --> UC255
am --> UC256
am --> UC257
am --> UC258
am --> UC259
@enduml
