from database import app, celery

from flask_covid19.blueprints.data_ecdc.ecdc_model_import import EcdcImport
from flask_covid19.blueprints.data_who.who_service_import import WhoImport
from flask_covid19.blueprints.data_vaccination.vaccination_model_import import VaccinationImport
from flask_covid19.blueprints.data_owid.owid_model_import import OwidImport
from flask_covid19.blueprints.data_rki.rki_model_import import RkiImport
from flask_covid19.blueprints.data_divi.divi_model_import import DiviImport

from flask_covid19.blueprints.data_ecdc.ecdc_model_import import EcdcFlat
from flask_covid19.blueprints.data_who.who_service_import import WhoFlat
from flask_covid19.blueprints.data_vaccination.vaccination_model_import import VaccinationFlat
from flask_covid19.blueprints.data_owid.owid_model_import import OwidFlat
from flask_covid19.blueprints.data_rki.rki_model_import import RkiFlat

from flask_covid19.blueprints.app_web.app_admin_service import AdminService
from flask_covid19.blueprints.app_web.user_service import UserService
from flask_covid19.blueprints.app_web.web_service import WebService

from flask_covid19.blueprints.data_ecdc.ecdc_service import EcdcService
from flask_covid19.blueprints.data_owid.owid_service import OwidService
from flask_covid19.blueprints.data_vaccination.vaccination_service import VaccinationService
from flask_covid19.blueprints.data_who.who_service import WhoService
from flask_covid19.blueprints.data_divi.divi_service import DiviService
from flask_covid19.blueprints.data_rki.rki_service import RkiService

from flask_covid19.blueprints.app_all.all_dispachter_matrix_service import AllDataServiceDispachterMatrix

from flask_covid19.blueprints.app_web.web_dispachter_matrix_service import app_admin_service
from flask_covid19.blueprints.app_web.web_dispachter_matrix_service import app_user_service
from flask_covid19.blueprints.app_web.web_dispachter_matrix_service import web_service
from flask_covid19.blueprints.app_web.web_dispachter_matrix_service import all_dispachter_matrix_service
