@startuml
left to right direction
'https://plantuml.com/class-diagram

package data_all.framework.model {

    abstract class AllEntity {}
}

package data_all.model {

    entity Task {}

    AllEntity <|- Task
}

@enduml
