@startuml
left to right direction

package covid19.blueprints.all.model_import {

	interface AllImportFull {
		{classifier} download_file()
		{classifier} import_file()
		{classifier} full_update_dimension_tables()
		{classifier} full_update_fact_table()
		{classifier} full_update_star_schema()
	}

	interface AllImportIncrement {
		{classifier} download_file()
		{classifier} import_file()
		{classifier} update_dimension_tables()
		{classifier} update_fact_table()
		{classifier} update_star_schema()
	}

	interface DataImport {
	    datum_reported: Date
		location: String
		location_group: String
		{classifier} download_file()
		{classifier} import_file()
		{classifier} full_update_dimension_tables()
		{classifier} full_update_fact_table()
		{classifier} full_update_star_schema()
		{classifier} update_dimension_tables()
		{classifier} update_fact_table()
		{classifier} update_star_schema()
	}
}

package covid19.blueprints.ecdc.model_import {

	entity EcdcImport {
	    id: Integer
		date_rep:  String
	    date_rep_day:  String
	    date_rep_month:  String
	    date_rep_year:  String
	    cases:  String
	    deaths:  String
	    pop_data_2019:  String
	    countries_and_territories:  String
	    geo_id:  String
	    country_territory_code:  String
	    continent_exp:  String
	    cumulative_number_for_14_days_of_covid19_cases_per_100000:  String
		{classifier} download_file()
		{classifier} import_file()
		{classifier} full_update_dimension_tables()
		{classifier} full_update_fact_table()
		{classifier} full_update_star_schema()
		{classifier} update_dimension_tables()
		{classifier} update_fact_table()
		{classifier} update_star_schema()
	}
}

AllImportFull <|-- DataImport
AllImportIncrement <|-- DataImport
DataImport <|-- EcdcImport

@enduml
