@startuml
package covid19.blueprints.app_user {
	actor AnonymousVisitor as vu
	actor AppManager as ou
	actor SysAdmin as su
	actor AppDevTester as du
}
package covid19.blueprints.app_user {
	vu <|-- ou
	vu <|-- su
	su <|-- du
	ou <|-- du
}
left to right direction
package user_views_frontend {
	usecase login as UC1
	usecase logout as UC2
	usecase profile_own as UC3
	usecase profile_own_edit as UC4
	usecase profile_list as UC5
	usecase profile_other as UC6
}
package user_views_for_tasks {
	usecase add_default_user as UC10
}

vu --> UC1
du --> UC2
du --> UC3
du --> UC4
su --> UC5
su --> UC6
su --> UC10
@enduml
