@startuml
left to right direction

package covid19.blueprints.all.model {

	interface AllDateReported {
	    id: Integer
		date_reported:  String
	    year_week:  String
	    datum: Date
	    year: Integer
	    month: Integerdocs/blueprints/app_web/uml/img/app_application_use_cases.png
	    day_of_month: Integer
	    day_of_week: Integer
	    week_of_year: Integer
		get_name_for_weekday()
		{classifier} get_names_for_weekday()onth: Integer, my_day: Integer)
		{classifier} get_datum_as_str(my_year: Integer, my_month: Integer, my_day: Integer)
		{classifier} my_year_week(my_iso_year: Integer, week_number: Integer)
		{classifier} create_new_object_factory(my_date_rep: String)
	}

	interface AllLocationGroup {
	    id: Integer
	    continent:  String
	    {classifier} remove_all()
	    {classifier} get_all_as_page(page: Integer)
	    {classifier} get_all()
	    {classifier} get_all_as_dict()
	    {classifier} get_by_id(other_id: Integer)
	    {classifier} find_by_id(other_id: Integer)
	}

	interface AllLocation {
	    id: Integer
    }

	interface AllData {
	    id: Integer
	}

}

package covid19.blueprints.ecdc.model {

	entity EcdcDateReported {
	    id: Integer
	    dateiname: String
	    parent_dir: String
	    title: String
	    path_relative: String
	    get_absolute_path()
	    get_relative_path()
	    {classifier} remove_all()
	    {classifier} get_all_as_page(page: Integer)
	    {classifier} get_all()
	    {classifier} get_all_as_dict()
	    {classifier} get_by_id(other_id: Integer)
	    {classifier} find_by_id(other_id: Integer)
	    {classifier} get_kurse_all()
	}

	entity EcdcContinent {
	    id: Integer
	    dateiname: String
	    parent_dir: String
	    get_absolute_path()
	    get_relative_path()
	    {classifier} remove_all()
	    {classifier} get_all_as_page(page: Integer)
	    {classifier} get_all()
	    {classifier} get_all_as_dict()
	    {classifier} get_by_id(other_id: Integer)
	    {classifier} find_by_id(other_id: Integer)
	    {classifier} get_workflow_for_id(workflow_id: Integer)
	}

	entity EcdcCountry {
	    id: Integer
	    dateiname: String
	    parent_dir: String
	    title: String
	    lektion_nr: Integer
	    verified: Boolean
	    get_absolute_path()
	    get_relative_path()
	    {classifier} remove_all()
	    {classifier} get_all_as_page(page: Integer)
	    {classifier} get_all()
	    {classifier} get_all_as_dict()
	    {classifier} get_by_id(other_id: Integer)
	    {classifier} find_by_id(other_id: Integer)
	    {classifier} get_lektionen_for_workflow(workflow: Workflow)
	    {classifier} get_lektion_for_id(lektion_id: Integer)
	    {classifier} get_folien_for_lektion_id(lektion_id: Integer)
	    {classifier} get_all_verified()
	}

	entity EcdcData {
	    id: Integer
	    dateiname: String
	    parent_dir: String
	    title: String
	    lektion_nr: Integer
	    foliensatz_nr_in_lektion: Integer
	    get_absolute_path()
	    get_relative_path()
	    {classifier} get_foliensaetze_for_lektion(lektion: Lektion)
	    {classifier} remove_all()
	    {classifier} get_all_as_page(page: Integer)
	    {classifier} get_all()
	    {classifier} get_all_as_dict()
	    {classifier} get_by_id(other_id: Integer)
	    {classifier} find_by_id(other_id: Integer)
	}
}

AllDateReported <|-- EcdcDateReported
AllLocationGroup <|-- EcdcContinent
AllLocation <|-- EcdcCountry

EcdcCountry "1" *--> "*" EcdcContinent: continent
EcdcData "1" *--> "*" EcdcCountry: country
EcdcData "1" *--> "*" EcdcDateReported: date_reported

@enduml
