@startuml
left to right direction

package project.data_all.model_import {

	interface AllImportFull {
		{classifier} download_file()
		{classifier} import_file()
		{classifier} full_update_dimension_tables()
		{classifier} full_update_fact_table()
		{classifier} full_update_star_schema()
	}

	interface AllImportIncrement {
		{classifier} download_file()
		{classifier} import_file()
		{classifier} update_dimension_tables()
		{classifier} update_fact_table()
		{classifier} update_star_schema()
	}

	interface AllImport {
	    datum_reported: Date
		location: String
		location_group: String
		{classifier} download_file()
		{classifier} import_file()
		{classifier} full_update_dimension_tables()
		{classifier} full_update_fact_table()
		{classifier} full_update_star_schema()
		{classifier} update_dimension_tables()
		{classifier} update_fact_table()
		{classifier} update_star_schema()
	}
}

package flask_covid19.data_rki.model_import {

	entity RkiImport {
		id: Integer
	    fid: String
	    id_bundesland: String
	    bundesland: String
	    landkreis: String
	    altersgruppe: String
	    geschlecht: String
	    anzahl_fall: String
	    anzahl_todesfall: String
	    meldedatum: String
	    id_landkreis: String
	    datenstand: String
	    neuer_fall: String
	    neuer_todesfall: String
	    ref_datum: String
	    neu_genesen: String
	    anzahl_genesen: String
	    ist_erkrankungsbeginn: String
	    altersgruppe2: String
		{classifier} download_file()
		{classifier} import_file()
		{classifier} full_update_dimension_tables()
		{classifier} full_update_fact_table()
		{classifier} full_update_star_schema()
		{classifier} update_dimension_tables()
		{classifier} update_fact_table()
		{classifier} update_star_schema()
	}
}

AllImportFull <|-- AllImport
AllImportIncrement <|-- AllImport
AllImport <|-- RkiImport

@enduml
