@startuml
package covid19.blueprints.app_user {
	actor AnonymousVisitor as vu
	actor AppManager as au
	actor SysAdmin as su
	actor AppDevTester as du
}
package covid19.blueprints.app_user {
	vu <|-- au
	vu <|-- su
	su <|-- du
	au <|-- du
}
left to right direction
package covid19.blueprints.app_admin.admin_views_frontend {
	usecase url_page_info as UC1
	usecase url_database_dump as UC50
	usecase url_database_dump_reimport as UC51
	usecase url_page_admin_crud as UC70
}
vu --> UC1
su --> UC1
su --> UC50
su --> UC51
su --> UC70
package covid19.blueprints.app_admin.admin_views_for_tasks {
	usecase url_alive_message as UC200
    usecase url_database_drop_create as UC201
    usecase url_database_drop as UC202
    usecase url_database_create as UC203
	usecase url_page_tasks as UC220
}
su --> UC200
su --> UC201
su --> UC202
su --> UC203
su --> UC220
package covid19.blueprints.app_admin.admin_celery_tasks {
	usecase task_alive_message as UC300
    usecase task_database_drop_create as UC301
    usecase task_database_drop as UC302
    usecase task_database_create as UC303
}
UC200 --> UC300
UC201 --> UC301
UC202 --> UC302
UC203 --> UC303
@enduml
