name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
    - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etc/requirements_linux.txt
    - name: venv
      run: make venv

    - name: activate dependencies
      run: . ./venv/bin/activate

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Node.js Dependencies
      run: npm install

    - name: Run start_linux
      run: make start_linux

    - name: Run linux
      run: make linux

