@startuml
package covid19.blueprints.app_user {
	actor AnonymousVisitor as vu
	actor AppManager as ou
	actor SysAdmin as su
	actor AppDevTester as du
}
package covid19.blueprints.app_user {
	vu <|-- ou
	vu <|-- su
	su <|-- du
	ou <|-- du
}
left to right direction
package owid_views_frontend {
	usecase owid_info as UC1
	usecase owid_imported as UC2
	usecase owid_date_reported as UC3
	usecase owid_date_continent as UC4
	usecase owid_date_country as UC5
	usecase owid_date_country_germany as UC6
	usecase owid_date_reports as UC7
}
package owid_views_for_tasks {
	usecase owid_tasks as UC57
	usecase task_owid_download_only as UC50
	usecase task_owid_import_only as UC51
	usecase task_owid_update_dimension_tables_only as UC52
	usecase task_owid_update_fact_table_initial_only as UC53
	usecase task_owid_update_fact_table_incremental_only as UC54
	usecase task_owid_update_star_schema_initial as UC55
	usecase task_owid_update_star_schema_incremental as UC56
}
package owid_celery_tasks {
	usecase owid_task_download_only as UC100
	usecase owid_task_import_only as UC101
	usecase owid_task_update_dimensiontables_only as UC102
	usecase owid_task_update_facttable_incremental_only as UC103
	usecase owid_task_update_facttable_initial_only as UC104
	usecase owid_task_update_starschema_initial as UC105
	usecase owid_task_update_starschema_incremental as UC106
}
vu --> UC1
vu --> UC2
vu --> UC3
vu --> UC4
vu --> UC5
vu --> UC6
vu --> UC7
au --> UC50
au --> UC51
au --> UC52
au --> UC53
au --> UC54
au --> UC55
au --> UC56
au --> UC57
UC50 --> UC100
UC51 --> UC101
UC52 --> UC102
UC53 --> UC103
UC54 --> UC104
UC55 --> UC105
UC56 --> UC106
@enduml